title: PiTrac 
description: Documentation for PiTrac
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Hackaday: https://hackaday.io/project/195042-pitrac-the-diy-golf-launch-monitor
